### ISSUE TITLE
发现个问题 如果回复序号以外的字符就会出现问题 是否可以优化一下

### ISSUE THREAD

**Issue by bhshuya** [Melodyknit/nonebot_plugin_animeres#2]
正常情况下 触发插件后会让你按序号选择资源类型 超出可选序号后会有提示
可是如果输入了其他的字符后插件就会报错 并且此次资源搜索会结束。。

  File "/admin/Nonebot_Bot_MayaFey/content/plugins/nonebot_plugin_animeres/__init__.py", line 33, in _
    if animes := cartoons.get((int(index) - 1) if index.isdigit() else index):
  File "/admin/Nonebot_Bot_MayaFey/content/plugins/nonebot_plugin_animeres/cartoon.py", line 121, in get
    return Cartoons(self.sort[key])
KeyError: '游戏'

是否可以优化一下 让错误的字符能有个提示 或者有更好的解决方案

**Comment by Melodyknit** [comment]
感谢您的问题反馈，我会尽快进行修复

**Comment by Melodyknit** [comment]
这个问题已经修复了，感谢您的反馈[be065e1](https://github.com/Melodyknit/nonebot_plugin_animeres/commit/be065e1ae8a9c1b599536fab6a855f4949ab91fc)

**Comment by Melodyknit** [comment]
已经对这个问题进行了修复，感谢您的反馈[01aa09e](https://github.com/Melodyknit/nonebot_plugin_animeres/commit/01aa09ed28c3b27cbb5fbfd3f5dc4114c2128dfc)

**Comment by Melodyknit** [comment]
已经对这个问题进行了修复[eca09fd](https://github.com/Melodyknit/nonebot_plugin_animeres/commit/eca09fd65ea00bec78604cf43fcf59c8f673cbc5)感谢您的反馈
