### ISSUE TITLE
找不到Awaitable

### ISSUE THREAD

**Issue by Cvandia** [Melodyknit/nonebot_plugin_animeres#3]
![image](https://user-images.githubusercontent.com/106718176/200710595-12bd3876-7188-4197-961f-a8575200471e.png)

**Comment by Melodyknit** [comment]
请问您使用的是什么版本的python

**Comment by Cvandia** [comment]
> 请问您使用的是什么版本的python

3.10,好像是被停用了

**Comment by Cvandia** [comment]
> 请问您使用的是什么版本的python

已解决，只要将cartoon.py中from collections import Awaitable改为from collections.abc import Awaitable 即可

**Comment by Melodyknit** [comment]
我从typing导入Awaitable
[6576294](https://github.com/Melodyknit/nonebot_plugin_animeres/commit/6576294856028517b1c9870f39ac502327b6ad74)

**Comment by Melodyknit** [comment]
> > 请问您使用的是什么版本的python
> 
> 已解决，只要将cartoon.py中from collections import Awaitable改为from collections.abc import Awaitable 即可

您从typing导入Awaitable应该也没问题吧
